exports.initialize = require('./Bootstrapper')
exports.dep        = require('./DependencySpec')
exports.events     = require('../sdk/Events')
exports.iterable   = require('../sdk/Iterable')
exports.decorators = require('./DecoratorManager')